apiVersion: apps/v1
kind: Deployment
metadata:
  name: adapter-container-deployment
  labels:
    env: prod
spec:
  replicas: 1
  selector:
    matchLabels:
      env: prod
  template:
    metadata:
      labels:
        env: prod
    spec:
      initContainers:
        - name: init-container
          image: alpine/git
          command: ["/bin/sh"]
          args:
            [
              "-c",
              "git clone https://github.com/RajPractiseRepo/Sidecar_Test.git /html"
            ]
          volumeMounts:
            - name: shared-vol
              mountPath: /tasks
      containers:
        - name: adapter-container
          image: busybox:1.28
          command: ["/bin/sh"]
          args:
            [
              "-c",
              "while true; do echo \\<h1\\>$(date)\\</h1\\> >> /html/index.html; sleep 5; done"
            ]
          volumeMounts:
            - name: shared-vol
              mountPath: /html/
        - name: main-container
          image: nginx:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          volumeMounts:
            - name: shared-vol
              mountPath: /usr/share/nginx/html/
      volumes:
        - name: shared-vol
          emptyDir: {}

---

apiVersion: v1
kind: Service
metadata:
  name: adapter-container-service
  labels:
    env: prod
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  selector:
    env: prod
  type: NodePort
